dd

diff --git a/.github/workflows/pr-master-deploy.yml b/.github/workflows/pr-master-deploy.yml
--- a/.github/workflows/pr-master-deploy.yml
+++ b/.github/workflows/pr-master-deploy.yml
@@ -65,14 +65,42 @@ jobs:
       - name: Checkout PR branch
         run: git checkout origin/pull/14/head
 
+
       - name: Force merge PR to main
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_USER }}
+          REPO_OWNER: gianfra901
+          REPO_NAME: app1-application
+          PR_NUMBER: 15
         run: |
-            git checkout main
-            git config --global user.name "github-actions[bot]"
-            git config --global user.email "github-actions[bot]@users.noreply.github.com"            
-            git merge --allow-unrelated-histories --strategy-option theirs origin/pull/14/head
-            git push origin main
-            token: ${{ secrets.GH_TOKEN_USER }}
+          # Obtener la información del PR
+          pr_data=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER")
+  
+          # Obtener la rama de la cabeza del PR
+          head_branch=$(echo "$pr_data" | jq -r .head.ref)
+  
+          # Realizar el merge
+          merge_response=$(curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
+            -d "{\"base\":\"main\",\"head\":\"$head_branch\",\"commit_message\":\"Force merge PR #$PR_NUMBER to main\"}" \
+            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/merges")
+  
+          # Verificar el resultado del merge
+          if echo "$merge_response" | grep -q '"sha":'; then
+            echo "Successfully merged PR #$PR_NUMBER to main."
+          else
+            echo "Failed to merge PR #$PR_NUMBER. Response: $merge_response"
+            exit 1
+          fi        
+
+    #   - name: Force merge PR to main
+    #     run: |
+    #         git checkout main
+    #         git config --global user.name "github-actions[bot]"
+    #         git config --global user.email "github-actions[bot]@users.noreply.github.com"            
+    #         git merge --allow-unrelated-histories --strategy-option theirs origin/pull/14/head
+    #         git push origin main
+    #         token: ${{ secrets.GH_TOKEN_USER }}
           
     #   - name: Force Merge Branch
     #     env:
